### ISSUE TITLE
When a character is entered instead of an integer, an infinite loop is executed.

### ISSUE THREAD

**Issue by Frixoe** [Frixoe/battleships#2]
isIncorrect() method checks for a character entered but can still somehow not detect a character. Problem seems to rise during input and the compiler reports InputMismatchException if not caught. Even after being caught, problem is persistent.

**Comment by dewoch2** [comment]
The problem is that when you call scanner.nextInt() and the character is not an integer, the character stays into your scanner object. If I were you, I would store scanner.next() which is a String into a local variable and then call Integer.parseInt() and manage the NumberFormatException.
Other point, I would make the playerAttacks method throws the NumberFormatException and deal with it in the loop because if it caught in the method itself, the cpu method will be called so the turn of the player is skipped.

**Comment by Frixoe** [comment]
Thank you so much @dewoch2! I have committed the changes you suggested but when I caught the **NumberFormatException** in **Main.java**, IntelliJ_(the IDE I'm using)_ gave me an error saying that the exception has already been caught. I checked several times if I had, only to find that I had not.

I ran the program without catching the **NumberFormatException** and entered a character, 'd' as the row. The program then displayed, 'For input string: "d"' and displayed the board without letting the CPU take its turn and asked for my turn again. Although it is doing what I wanted it to do, I would like the freedom to modify the display message at my will. Your assistance is greatly appreciated here.

I have a few questions though. What if I just _type-casted_ the _scanner.nextInt()_ instead of parsing it? Could I catch an exception made while _type casting_? And I still don't understand how this could trigger an infinite loop, please explain if you can.

Thank you so much for your contribution again! I truly appreciate it.

**Comment by dewoch2** [comment]
Hello Frixoe. NumberFormatException is a subclass of IllegalArgumentException (https://docs.oracle.com/javase/7/docs/api/java/lang/NumberFormatException.html). In Java, if you catch an exception which is a subclass of another exception, you must catch it before the super class exception (otherwise, your catch block is unreachable). Always put must specifics exception before less specifics ones. In your case, the NumberFormatException have been caught by the IllegalArgumentException block. In other words, you must put your catch block of NumberFormatException before the IllegalArgumentException one. (or you can manage the message you want to display in the IllegalArgumentException block but I suggest to add the NumberFormatException, it is better).

**Comment by dewoch2** [comment]
You can also think of manage a boolean if you don't want to display the board everytime there is a bad number exception. I pushed a suggestion on the fork I made (https://github.com/dewoch2/battleships.git).

**Comment by dewoch2** [comment]
"I have a few questions though. What if I just type-casted the scanner.nextInt() instead of parsing it? Could I catch an exception made while type casting? And I still don't understand how this could trigger an infinite loop, please explain if you can."
If you type cast you will still have the same issue. Let me try to explain you:  when you enter a character, this character is "stored" into your scanner object. So at this stage, the scanner object contains a character. 
In first case, let's say this character is an integer. If you call nextInt, the character that is stored is returned and removed from the scanner object. So the scanner object is now empty and everything goes well.
Now let's say the character is not an integer but a String instead. You call nextInt. Imagine that this method internally tries to call Integer.parseInt(value). It means before trying to remove the value from the current scanner object, it throws an exception. As a consequence, scanner object is not empty.

Now, the fact you are in a while loop, each time you reach scanner.nextInt, it doesn't wait for the user input because the scanner object is not empty so it processes the character that it contains as being the entered character and the exception is thrown again without the character has been removed and so on...
I hope I have been clear.

**Comment by Frixoe** [comment]
Thank you again for explaining everything to me @dewoch2 . I clearly didn't understand what the scanner.nextInt() method did. I was under the impression that it gave an error as soon as it received a non-integer.

Wow, I didn't even think of managing a boolean to display the boards. That's brilliant! I have committed the changes in the original repo. I will be closing this issue upon your reply.

I really appreciate your assistance in this matter. Thank you so much!
